apiVersion: v1
kind: Pod
metadata:
  name: dynamic-pod
spec:
  containers:
    - name: busybox
      image: busybox:latest
      command:
        - sh
        - -c
        - |
          echo "Dynamic PV data $(date)" > /data/message.txt
          cat /data/message.txt
          sleep 3600
      volumeMounts:
        - name: dynamic-storage
          mountPath: /data
  volumes:
    - name: dynamic-storage
      persistentVolumeClaim:
        claimName: pvc-dynamic
  restartPolicy: Never
