[ubuntu_web]
worker-ubuntu ansible_host=18.222.187.158 ansible_user=ubuntu

[redhat_app]
worker-redhat ansible_host=18.224.199.164 ansible_user=ec2-user

[amz_db]
worker-amazon ansible_host=3.22.99.133 ansible_user=ec2-user

[servers]
worker-amazon
worker-redhat
worker-ubuntu

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_private_key_file=./terra-automate-key

[application:children]
ubuntu_web
redhat_app

[all_servers:children]
application
amz_db
