[ubuntu_web]
worker-ubuntu ansible_host=18.217.142.150 ansible_user=ubuntu

[redhat_app]
worker-redhat ansible_host=3.129.14.230 ansible_user=ec2-user

[amz_db]
worker-amazon ansible_host=18.117.90.177 ansible_user=ec2-user

[servers]
worker-amazon
worker-redhat
worker-ubuntu

[servers:vars]
ansible_python_interpreter=/usr/bin/python3
