[web]
worker-ubuntu ansible_host=3.16.215.123 ansible_user=ubuntu

[app]
worker-redhat ansible_host=3.21.167.210 ansible_user=ec2-user

[db]
worker-amazon ansible_host=18.219.126.54 ansible_user=ec2-user

[servers]
worker-amazon
worker-redhat
worker-ubuntu

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_private_key_file=./terra-automate-key

[application:children]
web
app

[all_servers:children]
application
db
