apiVersion: v1
kind: Pod
metadata:
  name: third-pod
  labels:
    app: myapp
    environment: test
    team: devops
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
